name: Build Docker image

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  docker:
    name: Build Docker Image
    uses: cupcakearmy/workflows/.github/workflows/docker.yml@main
    with:
      name: cupcakearmy/ddns-cloudflare
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
