name: Publish Docker image

on:
  release:
    types:
      - published

jobs:
  docker:
    name: Build Docker Image
    uses: cupcakearmy/workflows/.github/workflows/docker.yml@main
    with:
      name: cupcakearmy/ddns-cloudflare
      push: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
